spring.application.name=siscom

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/siscom}

spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}

spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
api.security.token.secret=${JWT_SECRET:minha-chave-secreta-super-segura-e-longa}

# spring.datasource.password=ifpb

# spring.datasource.username=${DB_USERNAME:postgres}
# spring.datasource.password=${DB_PASSWORD:changeMe}
# api.security.token.secret=${JWT_SECRET:generateAndChangeInProduction}


#logging.level.org.springframework.messaging=DEBUG

#logging.level.org.springframework.web.socket=DEBUG

server.servlet.context-path=/api/siscom



spring.jpa.hibernate.ddl-auto=update

# Adiciona a configuração de CORS
app.cors.allowed-origins=http://localhost:4200,http://localhost:3000

# Ativa os logs detalhados do Spring Security
# logging.level.org.springframework.security=DEBUG
# # Opcional: Ativa os logs do gerenciador de filtros da web
# logging.level.org.springframework.web.filter=DEBUG

# Configurar levels de log
logging.level.root=WARN
logging.level.br.gov.siscom=INFO
logging.level.AUDIT=INFO
logging.level.REQUEST=DEBUG

# Formato customizado
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Proteção contra DoS e Limite de Memória (Timeouts)
# Derruba requisições que demorarem mais de 5 segundos
server.tomcat.connection-timeout=5000
spring.mvc.async.request-timeout=5000

# Bloqueia corpos de requisição gigantescos
server.tomcat.max-http-form-post-size=2MB


server.port=${PORT:8080}