spring.application.name=siscom

spring.datasource.url=jdbc:postgresql://localhost:5432/siscom

spring.datasource.username=postgres

spring.datasource.password=ifpb

logging.level.org.springframework.messaging=DEBUG

logging.level.org.springframework.web.socket=DEBUG